name: package-deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  package:
    name: "package"
    runs-on: ubuntu-latest

    steps:
      # Checkout source codes
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt;
      # package application into BUILD directory
      - name: Create BUILD directory and copy necessary application files
        run: |
          mkdir BUILD
          cp -r static BUILD/static  # copy the static directory and contents
          cp -r templates BUILD/templates  # copy the templates directory and contents
          cp -r app.py BUILD/app.py
          cp -r requirements.txt BUILD/requirements.txt
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            ./BUILD
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'VTMPIPELINE'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6C9CED6F5A5D432FA326F29658BDF823 }}